//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddCompetition.
        /// </summary>
        public static string AddCompetition {
            get {
                return ResourceManager.GetString("AddCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddSkater.
        /// </summary>
        public static string AddSkater {
            get {
                return ResourceManager.GetString("AddSkater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddTeam.
        /// </summary>
        public static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CategoryWithColon.
        /// </summary>
        public static string CategoryWithColon {
            get {
                return ResourceManager.GetString("CategoryWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DeleteCcompetition.
        /// </summary>
        public static string DeleteCompetition {
            get {
                return ResourceManager.GetString("DeleteCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DeleteCompetitionContent.
        /// </summary>
        public static string DeleteCompetitionContent {
            get {
                return ResourceManager.GetString("DeleteCompetitionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DeleteSkater.
        /// </summary>
        public static string DeleteSkater {
            get {
                return ResourceManager.GetString("DeleteSkater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DeleteSkaterContent.
        /// </summary>
        public static string DeleteSkaterContent {
            get {
                return ResourceManager.GetString("DeleteSkaterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DeleteTeam.
        /// </summary>
        public static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DeleteTeamContent.
        /// </summary>
        public static string DeleteTeamContent {
            get {
                return ResourceManager.GetString("DeleteTeamContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DescriptionWithColon.
        /// </summary>
        public static string DescriptionWithColon {
            get {
                return ResourceManager.GetString("DescriptionWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @EditCompetition.
        /// </summary>
        public static string EditCompetition {
            get {
                return ResourceManager.GetString("EditCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @EditSkater.
        /// </summary>
        public static string EditSkater {
            get {
                return ResourceManager.GetString("EditSkater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @EditTeam.
        /// </summary>
        public static string EditTeam {
            get {
                return ResourceManager.GetString("EditTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @EndDateWithColon.
        /// </summary>
        public static string EndDateWithColon {
            get {
                return ResourceManager.GetString("EndDateWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FilterCompetitionsList.
        /// </summary>
        public static string FilterCompetitionsList {
            get {
                return ResourceManager.GetString("FilterCompetitionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IdentityNumberWithColon.
        /// </summary>
        public static string IdentityNumberWithColon {
            get {
                return ResourceManager.GetString("IdentityNumberWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LastNamesWithColon.
        /// </summary>
        public static string LastNamesWithColon {
            get {
                return ResourceManager.GetString("LastNamesWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NameWithColon.
        /// </summary>
        public static string NameWithColon {
            get {
                return ResourceManager.GetString("NameWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NumberWithColon.
        /// </summary>
        public static string NumberWithColon {
            get {
                return ResourceManager.GetString("NumberWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SelectCompetition.
        /// </summary>
        public static string SelectCompetition {
            get {
                return ResourceManager.GetString("SelectCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SexWithColon.
        /// </summary>
        public static string SexWithColon {
            get {
                return ResourceManager.GetString("SexWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Skaters.
        /// </summary>
        public static string Skaters {
            get {
                return ResourceManager.GetString("Skaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @StartDateWithColon.
        /// </summary>
        public static string StartDateWithColon {
            get {
                return ResourceManager.GetString("StartDateWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @TeamWithColon.
        /// </summary>
        public static string TeamWithColon {
            get {
                return ResourceManager.GetString("TeamWithColon", resourceCulture);
            }
        }
    }
}
